version: "3"
services:
  bot:
    build: .
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    volumes:
      - ./watching_users.json:/app/watching_users.json
      - ./cash_watchers.json:/app/cash_watchers.json
